### ISSUE TITLE
打完包了导致错误，nul

### ISSUE THREAD

**Issue by parlay96** [unplugin/unplugin-vue#148]
### Describe the bug

![image](https://github.com/unplugin/unplugin-vue/assets/32978177/b906e286-3433-400c-ae75-024ccaffca33)
![image](https://github.com/unplugin/unplugin-vue/assets/32978177/5cf9646a-5749-462b-a4f1-33bba21aad27)

### Reproduction

no

### System Info

```Shell
win
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
This is expected behavior
