### ISSUE TITLE
Non-descriptive errors with esbuild

### ISSUE THREAD

**Issue by mcrampon** [unplugin/unplugin-vue#149]
### Describe the bug

When using unplugin-vue with esbuild, I get error messages that I can't really use.

![image](https://github.com/unplugin/unplugin-vue/assets/6572765/7ca9d9f5-3b8d-4d8e-930b-5bc749766b8a)

From what I could diagnose, this comes from this line: https://github.com/unplugin/unplugin-vue/blob/d17f4dcc3bc511d0deb43dd0d372fffdb21fa0b6/src/core/template.ts#L106

I would guess that esbuild doesn't really do anything with objects here and would rather get a string

### Reproduction

unplugin-vue 5.0.2 + esbuild 0.20.0

Example of a component that will produce such an error:

```vue
<template>
  <MyComponent v-model="myProp" />
</template>
<script>
export default {
  props: {
    myProp: {
      type: String,
      required: true
    }
  }
};
</script>
```

The error message should be something like:
```
  SyntaxError: v-model cannot be used on a prop, because local prop bindings are not writable.
  Use a v-bind binding combined with a v-on listener that emits update:x event instead.
```

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
    Memory: 1.23 GB / 11.50 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v18.19.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Fixed!

**Comment by sxzz** [comment]
Try `unplugin-vue@5.0.3`
