### ISSUE TITLE
v-else on template element throws error

### ISSUE THREAD

**Issue by mcrampon** [unplugin/unplugin-vue#152]
### Describe the bug

When using the `v-else` directive on `template`, I get an error:

```vue
<template>
  <my-modal>
    <template v-if="foo" #body>
      Something if foo is truthy
    </template>
    <template v-else #body>
      Something if foo is falsy
    </template>
  </my-modal>
</template>
```

```
✘ [ERROR] v-else/v-else-if has no adjacent v-if or v-else-if. [plugin vue]

    components/my_component.vue:6:0:
      6 │ 
        ╵ ^
```

### Reproduction

esbuild@0.20.1 + unplugin-vue@5.0.3 + vue@3.4.19

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
    Memory: 2.33 GB / 11.50 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v18.19.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Browsers:
    Chrome: 121.0.6167.184
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Cannot reproduce. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by mcrampon** [comment]
Here's a more detailed reproduction:

```vue
<!-- slotter.vue -->
<template>
  <slot name="body" />
</template>
```

```vue
<!-- slotted.vue -->
<template>
  <slotter>
    <template v-if="true" #body>
      Something
    </template>
    <template v-else #body>
      Something else
    </template>
  </slotter>
</template>

<script>
import Slotter from './slotter.vue';

export default {
  components: {
    Slotter
  }
};
</script>
```

```
✘ [ERROR] v-else/v-else-if has no adjacent v-if or v-else-if. [plugin vue]

    components/slotted.vue:6:0:
      6 │ 
        ╵ ^
```

**Comment by sxzz** [comment]
Still cannot reproduce. Please at least submit a reproduction repo (GitHub repo) that within the basic setup.


Plus, looks like the errors are not caused by `unplugin-vue` itself, could be caused by Vue Compiler.
