### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by SelfhostedPro** [unplugin/unplugin-vue#154]
### Clear and concise description of the problem

Hey, I was wondering if there was any documentation available for what options there are and how to configure them?

I'm working on an SSR app using vite, rollup, and hono and have been running into issues but can't figure out where to look for configuration options.

### Suggested solution

Write some documentation or provide info on configuration options and I'd be happy to contribute.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Same of `@vitejs/plugin-vue`, please refer to https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue#options
